---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-gitops-operator
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      environment: "lab"
  remediationAction: inform
policies:
  - name: install-gitops-operator
    manifests:
    - path: gitops-operator.yaml
