---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-compliance-operator
policyDefaults:
  namespace: policies
  placement:
## to which cluster policy should apply to
    clusterSelectors:
      environment: "lab"
  remediationAction: enforce
policies:
  - name: install-compliance-operator
    manifests:
    - path: compliance-operator.yaml
